---
- name: Enable & start StrongSwan
  service:
    name: ipsec
    state: started
    enabled: yes

- name: Redémarrer StrongSwan
  service:
    name: strongswan-starter
    state: restarted

- name: Check ipsec status
  shell: ipsec statusall || true
  register: ipsec_status

- debug:
    var: ipsec_status.stdout
