---
- name: Installer StrongSwan et dépendances
  ansible.builtin.apt:
    name:
      - strongswan
      - strongswan-pki
      - libstrongswan-extra-plugins
      - iproute2
      - net-tools
    state: present
    update_cache: yes
