---
- name: Nettoyage de l'environnement VPN
  hosts: vpn_server
  become: yes
  tasks:
    - name: Stop StrongSwan
      service:
        name: strongswan-starter
        state: stopped
      ignore_errors: yes

    - name: Remove ipsec.conf
      file:
        path: /etc/ipsec.conf
        state: absent

    - name: Remove ipsec.secrets
      file:
        path: /etc/ipsec.secrets
        state: absent

    - name: Clear ipsec.d
      file:
        path: /etc/ipsec.d
        state: absent

    - name: Clear logs strongswan
      file:
        path: /var/log/strongswan
        state: absent
